# https://raw.githubusercontent.com/loutfinadir/http/main/data/classification/applyout/APPLY_1M.csv
# https://raw.githubusercontent.com/loutfinadir/http/main/data/classification/applyout/apply_census_v1.csv

### Post data on Job
POST https://ppro-firefly-dis-sac-orcastarkiller.cfapps.sap.hana.ondemand.com/cloud/dis/jobs/{{jobID}} HTTP/1.1
x-csrf-token: Fetch
Authorization: {{accessTechToken}}
x-sap-boc-tenant-id: {{X-Sap-Boc-Tenant-id}}
x-sap-boc-approuter-orca-context: {{X-Sap-Boc-Approuter-Orca-Context}}
#x-sap-boc-impersonated-user: {{impersonatedUser}}
impersonated-user: {{impersonatedUser}}
Content-Type: text/plain
Accept: application/json

https://raw.githubusercontent.com/loutfinadir/http/main/data/classification/applyout/SSN.csv