
###
POST https://{{dataimportservice}}/models/{{modelID}} HTTP/1.1
Authorization: {{accessTechToken}}
x-sap-boc-approuter-orca-context: {{X-Sap-Boc-Approuter-Orca-Context}}
x-sap-boc-impersonated-user: {{impersonatedUser}}
x-sap-boc-tenant-id: {{X-Sap-Boc-Tenant-id}}
Content-Type: application/json

{
    "DefaultValues": {
        "Version": "public.census_apply",
        "date": "2024-01-01"
    },
    "Mapping": {
        "SSN" : "SSN",
        "education" : "education",
        "income" : "income",
        "marital_status" : "marital_status",
        "native_country" : "native_country",
        "occupation" : "occupation",
        "PredictedCategory" : "PredictedCategory",
        "race" : "race",
        "relationship" : "relationship",
        "sex" : "sex",
        "workclass":  "workclass",
        "ExplanationInfluencer" : "ExplanationInfluencer",
        "ExplanationInfluencerValue" : "ExplanationInfluencerValue",
        "ExplanationRank" : "ExplanationRank",
        "OutlierIndicator" : "OutlierIndicator",
        "ExplanationStrength": "ExplanationStrength",
        "PredictionProbability": "PredictionProbability",
        "date" : "date",
        "Version" : "Version",
        
        "age" : "age",
        "capital_gain" : "capital_gain",
        "capital_loss" : "capital_loss",
        "hours_per_week" : "hours_per_week",
        "fnlwgt" : "fnlwgt",
        "education_num" : "education_num"

    }
}

### push data
POST https://{{dataimportservice}}/jobs/{{jobID}} HTTP/1.1
Authorization: {{accessTechToken}}
x-csrf-token: {{X-Csrf-Token}}
x-sap-boc-tenant-id: {{X-Sap-Boc-Tenant-id}}
x-sap-boc-approuter-orca-context: {{X-Sap-Boc-Approuter-Orca-Context}}
x-sap-boc-impersonated-user: {{impersonatedUser}}
Content-Type: application/json
Accept: application/json

{
  "DefaultValues": {
    "Version": "public.census_apply",
    "date": "2024-01-01"
  },
  "Mapping": {
    "SSN": "SSN",
    "education": "education",
    "income": "income",
    "marital_status": "marital_status",
    "native_country": "native_country",
    "occupation": "occupation",
    "PredictedCategory": "PredictedCategory",
    "race": "race",
    "relationship": "relationship",
    "sex": "sex",
    "workclass": "workclass",
    "ExplanationInfluencer": "ExplanationInfluencer",
    "ExplanationInfluencerValue": "ExplanationInfluencerValue",
    "ExplanationRank": "ExplanationRank",
    "OutlierIndicator": "OutlierIndicator",
    "ExplanationStrength": "ExplanationStrength",
    "PredictionProbability": "PredictionProbability",
    "date": "date",
    "Version": "Version",
    
    "age" : "age",
    "capital_gain" : "capital_gain",
    "capital_loss" : "capital_loss",
    "hours_per_week" : "hours_per_week",
    "fnlwgt" : "fnlwgt",
    "education_num" : "education_num"
  },
  "Data": [
    {
      "SSN": 1,
      "education": "HS-grad",
      "income": "<=50K",
      "marital_status": "Widowed",
      "native_country": "United-States",
      "occupation": "?",
      "PredictedCategory": "<=50K",
      "race": "White",
      "relationship": "Not-in-family",
      "sex": "Female",
      "workclass": "?",
      "ExplanationInfluencer": "#",
      "ExplanationInfluencerValue": "#",
      "ExplanationRank": "0",
      "OutlierIndicator": "#",
      "ExplanationStrength": 0,
      "PredictionProbability": 0.175857946,
      "age" : 90,
      "capital_gain" : 0,
      "capital_loss" : 4356,
      "hours_per_week" : 40,
      "fnlwgt" : 77053,
      "education_num" : 9
    }
  ]
}

### validate job
POST https://{{dataimportservice}}/jobs/{{jobID}}/validate HTTP/1.1
Authorization: {{accessTechToken}}
x-sap-boc-tenant-id: {{X-Sap-Boc-Tenant-id}}
x-sap-boc-approuter-orca-context: {{X-Sap-Boc-Approuter-Orca-Context}}
x-sap-boc-impersonated-user: {{impersonatedUser}}
Content-Type: application/json
Accept: application/json


### run job
POST https://{{dataimportservice}}/jobs/{{jobID}}/run HTTP/1.1
Authorization: {{accessTechToken}}
x-sap-boc-approuter-orca-context: {{X-Sap-Boc-Approuter-Orca-Context}}
x-sap-boc-impersonated-user: {{impersonatedUser}}
x-sap-boc-tenant-id: {{X-Sap-Boc-Tenant-id}}
Content-Type: application/json
Accept: application/json

### job status
GET https://{{dataimportservice}}/jobs/{{jobID}}/status HTTP/1.1
Authorization: {{accessTechToken}}
x-sap-boc-approuter-orca-context: {{X-Sap-Boc-Approuter-Orca-Context}}
x-sap-boc-impersonated-user: {{impersonatedUser}}
x-sap-boc-tenant-id: {{X-Sap-Boc-Tenant-id}}
Content-Type: application/json
Accept: application/json


###
DELETE https://{{dataimportservice}}/jobs/{{jobID}} HTTP/1.1
Authorization: {{accessTechToken}}
x-sap-boc-approuter-orca-context: {{X-Sap-Boc-Approuter-Orca-Context}}
x-sap-boc-impersonated-user: {{impersonatedUser}}
x-sap-boc-tenant-id: {{X-Sap-Boc-Tenant-id}}
Content-Type: application/json
Accept: application/json

----
- During the import, when creating the job, all dimensions and measures in the model must be included. The dimensions constitute the primary keys of the model. As for the measures, they must also be included so that during the import their respective values can be passed; otherwise, they will have "null" as the default value.
- Models should not contain dimensions with some having the "dimension table" option enabled and others not: This causes an issue during data import. 
    The data import service cannot handle dimensions with the "dimension table" option enabled and others not. Therefore, it is necessary to disable the "dimension table" option for all dimensions in the model.
