### Post data on Job
# https://raw.githubusercontent.com/loutfinadir/http/main/data/classification/applyout/apply_500.csv
POST https://ppro-firefly-dis-sac-orcastarkiller.cfapps.sap.hana.ondemand.com/cloud/v2/dis/jobs/{{jobID}} HTTP/1.1
Authorization: {{accessTechToken}}
x-sap-boc-approuter-orca-context: {{X-Sap-Boc-Approuter-Orca-Context}}
x-sap-boc-impersonated-user: {{impersonatedUser}}
Content-Type: text/plain
Accept: application/json

https://raw.githubusercontent.com/loutfinadir/http/refs/heads/main/data/classification/applyout/census-with-predictors-min-rows.csv
