# https://raw.githubusercontent.com/loutfinadir/http/main/data/classification/applyout/APPLY_1M.csv
# https://raw.githubusercontent.com/loutfinadir/http/main/data/classification/applyout/apply_census_v1.csv

### Post data on Job
POST https://ppro-firefly-dis-sac-orcastarkiller.cfapps.sap.hana.ondemand.com/cloud/dis/jobs/{{jobID}} HTTP/1.1
x-csrf-token: Fetch
Authorization: {{accessTechToken}}
x-sap-boc-tenant-id: {{X-Sap-Boc-Tenant-id}}
x-sap-boc-approuter-orca-context: {{X-Sap-Boc-Approuter-Orca-Context}}
#x-sap-boc-impersonated-user: {{impersonatedUser}}
impersonated-user: {{impersonatedUser}}
Content-Type: text/plain
Accept: application/json

https://raw.githubusercontent.com/loutfinadir/http/main/data/classification/applyout/apply_with_column_version.csv



####
POST https://{{dataimportservice}}/jobs/c5d5be52-be61-479c-ad84-8420d2bfc73d HTTP/1.1
Authorization: {{accessTechToken}}
x-csrf-token: Fetch
x-sap-boc-tenant-id: e647d8a0-9ea6-4142-890e-38a14939e3da
x-sap-boc-approuter-orca-context: {"orcaTenantId":"X","orcaTenantName":"E80F1","orcaTenantUuid":"e647d8a0-9ea6-4142-890e-38a14939e3da","orcaTenantLocalId":"X"}
x-sap-boc-impersonated-user: X_NADIR_NOADMIN
Content-Type: application/json
Accept: application/json

{
  "Data": [
    {
      "SSN": "1",
      "ExplanationInfluencer": "",
      "ExplanationInfluencerValue": "0",
      "ExplanationRank": "0",
      "PredictedCategory": "0",
      "OutlierIndicator": null,
      "ExplanationStrength": "",
      "PredictionProbability": 0.36
    },
    {
      "SSN": "1",
      "ExplanationInfluencer": "age",
      "ExplanationInfluencerValue": "48",
      "ExplanationRank": "1",
      "PredictedCategory": null,
      "OutlierIndicator": null,
      "ExplanationStrength": "",
      "PredictionProbability": 0.95
    }
  ]
}


