### validate job
POST https://{{dataimportservice}}/jobs/{{jobID}}/validate HTTP/1.1
x-csrf-token: Fetch
Authorization: {{accessTechToken}}
x-sap-boc-tenant-id: {{X-Sap-Boc-Tenant-id}}
x-sap-boc-approuter-orca-context: {{X-Sap-Boc-Approuter-Orca-Context}}
x-sap-boc-impersonated-user: {{impersonatedUser}}
Content-Type: application/json
Accept: application/json


### validate job
POST https://{{dataimportservice}}/jobs/8df44f52-be38-4e76-9c17-00d0c2745e82/validate HTTP/1.1
x-csrf-token: Fetch
Authorization: {{accessTechToken}}
x-sap-boc-tenant-id: e647d8a0-9ea6-4142-890e-38a14939e3da
x-sap-boc-approuter-orca-context: {"orcaTenantId":"X","orcaTenantName":"E80F1","orcaTenantUuid":"e647d8a0-9ea6-4142-890e-38a14939e3da","orcaTenantLocalId":"X"}
x-sap-boc-impersonated-user: X_NADIR_NOADMIN
Content-Type: application/json
Accept: application/json